[0] [12:39:04 17-12-22] [LOGGER] -- : checking log files
[1] [12:39:04 17-12-22] [CORE] -- : log files are checked
[2] [12:39:04 17-12-22] [CORE] -- : Machine started
[3] [12:39:04 17-12-22] [CREATE_PROTOCOL] -- : Protocol successfully created
[4] [12:39:04 17-12-22] [CORE] -- : Processing successfully completed
[5] [12:39:04 17-12-22] [LOGIN] -- : trying to login
[6] [12:39:08 17-12-22] [LOGIN] -- : an error detected: OpenSSL::SSL::SSLError SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed ["C:/Ruby23/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock'", "C:/Ruby23/lib/ruby/2.3.0/net/http.rb:933:in `connect'", "C:/Ruby23/lib/ruby/2.3.0/net/http.rb:863:in `do_start'", "C:/Ruby23/lib/ruby/2.3.0/net/http.rb:858:in `start'", "C:/Ruby23/lib/ruby/gems/2.3.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:700:in `start'", "C:/Ruby23/lib/ruby/gems/2.3.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:631:in `connection_for'", "C:/Ruby23/lib/ruby/gems/2.3.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:994:in `request'", "C:/Ruby23/lib/ruby/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:274:in `fetch'", "C:/Ruby23/lib/ruby/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize.rb:464:in `get'", "F:/EVOKE/Ruby/instabot.rb/instabot.rb/lib/instabot/login.rb:13:in `login'", "F:/EVOKE/Ruby/instabot.rb/instabot.rb/lib/instabot/core.rb:103:in `intro'", "F:/EVOKE/Ruby/instabot.rb/instabot.rb/lib/instabot/core.rb:57:in `initialize'", "F:/EVOKE/Ruby/instabot.rb/instabot.rb/examples/automatic_example.rb:34:in `new'", "F:/EVOKE/Ruby/instabot.rb/instabot.rb/examples/automatic_example.rb:34:in `<main>'"]
